
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POW = 21;
  public static final int GE = 14;
  public static final int INTEGER_CONST = 49;
  public static final int INTEGER = 45;
  public static final int SEMI = 9;
  public static final int OUT = 4;
  public static final int MINUS = 25;
  public static final int WRITE = 31;
  public static final int NOT = 11;
  public static final int WRITET = 28;
  public static final int AND = 13;
  public static final int LT = 17;
  public static final int RPAR = 40;
  public static final int FUN = 38;
  public static final int OR = 12;
  public static final int BOOL = 42;
  public static final int COMMA = 8;
  public static final int DIV = 22;
  public static final int LOOP = 3;
  public static final int PLUS = 26;
  public static final int MAIN = 46;
  public static final int IF = 36;
  public static final int ASSIGN = 27;
  public static final int WRITELN = 30;
  public static final int ID = 52;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int WRITEB = 29;
  public static final int RETURN = 7;
  public static final int TRUE = 47;
  public static final int error = 1;
  public static final int NULL = 10;
  public static final int DIVINT = 23;
  public static final int EQ = 19;
  public static final int REAL = 43;
  public static final int OUTPAR = 6;
  public static final int TIMES = 24;
  public static final int COLON = 39;
  public static final int ELSE = 34;
  public static final int READ = 32;
  public static final int _uminus = 2;
  public static final int WHILE = 33;
  public static final int STR_CONCAT = 20;
  public static final int REAL_CONST = 50;
  public static final int THEN = 35;
  public static final int NE = 18;
  public static final int END = 37;
  public static final int STRING = 44;
  public static final int LPAR = 41;
  public static final int FALSE = 48;
  public static final int STRING_CONST = 51;
  public static final int GT = 15;
  public static final int VAR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "_uminus",
  "LOOP",
  "OUT",
  "VAR",
  "OUTPAR",
  "RETURN",
  "COMMA",
  "SEMI",
  "NULL",
  "NOT",
  "OR",
  "AND",
  "GE",
  "GT",
  "LE",
  "LT",
  "NE",
  "EQ",
  "STR_CONCAT",
  "POW",
  "DIV",
  "DIVINT",
  "TIMES",
  "MINUS",
  "PLUS",
  "ASSIGN",
  "WRITET",
  "WRITEB",
  "WRITELN",
  "WRITE",
  "READ",
  "WHILE",
  "ELSE",
  "THEN",
  "IF",
  "END",
  "FUN",
  "COLON",
  "RPAR",
  "LPAR",
  "BOOL",
  "REAL",
  "STRING",
  "INTEGER",
  "MAIN",
  "TRUE",
  "FALSE",
  "INTEGER_CONST",
  "REAL_CONST",
  "STRING_CONST",
  "ID"
  };
}

